version: '1.0'

services:
  nginx:
    container_name: nginx
    image: bitnami/nginx:1.23
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/app
      - ./nginx_conf/default.conf:/opt/bitnami/nginx/conf/server_blocks/default.conf
      - ./nginx_conf/certs:/etc/nginx/certs/self-signed
    networks:
      - lemp-network

  mariadb:
    container_name: mariadb
    image: bitnami/mariadb:10.10
    restart: always
    env_file: .env
    # environment:
      # all environment info declared in .env file
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb_data:/bitnami/mariadb
    networks:
      - lemp-network

  php:
    depends_on:
      - nginx
      - mariadb
    container_name: php
    image: bitnami/php-fpm:8.2
    restart: always
    volumes:
      - ./app:/app
    networks:
      - lemp-network

  phpmyadmin:
    depends_on:
      # - nginx
      - mariadb
      # - php
    container_name: phpmyadmin
    # image: phpmyadmin:5.2.0
    image: bitnami/phpmyadmin:5.2.0
    restart: always
    # env_file: .env
    ports:
      - "3307:8080"
      - '3308:443'
    environment:
      #PMA_HOST: database
      #MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      - DATABASE_ALLOW_NO_PASSWORD=false
      - PHPMYADMIN_ALLOW_ARBITRARY_SERVER=yes
      # - PMA_ARBITRARY=1
    networks:
      - lemp-network

networks:
  lemp-network:
    
volumes:
  app:
  mariadb_data:
  nginx_conf:
    #driver: local
    #driver: bridge

    